version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database_ma
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  

  app:
    build: .
    command: sh start.sh
    volumes:
      - .:/app
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASS: password
      DB_NAME: database_ma
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - database

volumes:
  db_data: