version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=database_ma
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: database_ma
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: