version: '3.8'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_ma
    volumes:
      - db_data:/var/lib/mysql
      - ./database_ma.sql:/docker-entrypoint-initdb.d/database_ma.sql
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - database

volumes:
  db_data: