version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_ma
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    command: sh start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: