version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - NODE_ENV=development
    depends_on:
      - database
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'database_ma'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: